### ISSUE TITLE
Bug in latest imscp Version

### ISSUE THREAD

**Issue by GrexAut** [saygoweb/imscp-letsencrypt#10]
Hi,

if I'm using this nice plugin, the SSL Cert at /var/www/imscp/gui/data/certs/$domain.pem is not the same as /etc/letsencrypt/live/$doamin/

So the SSL Cert is invalid, as I read in source code, there will be used a tmp SSL Cert, but it should be deleted, right?
![grafik](https://user-images.githubusercontent.com/5990312/36647335-3a1dff20-1a84-11e8-840d-0f280f893f91.png)

**Comment by cambell-prince** [comment]
I'm guessing you're using i-MSC v1.4.x?  I get an error along those lines in that version.  Currently the plugin only supports i-MSCP v1.3.x.  I've created #13 as the feature request to support newer i-MSCP versions.
