### ISSUE TITLE
Does not work from install on i-MSCP 1.5.3

### ISSUE THREAD

**Issue by excodex** [saygoweb/imscp-letsencrypt#16]
Hi,

When I try to access the LetsEncrypt submenu on the left side, i-MSCP throws an error.

**Comment by cambell-prince** [comment]
LetsEncrypt submenu in the reseller menu or user menu? Can you provide details as to the error? Was anything apparent in the plugin logs (see the admin | settings section of i-MSCP).  Can you confirm that the plugin folder name is `LetsEncrypt`.

**Comment by excodex** [comment]
Yes, I'm sorry, here is the detailed steps:

1. I downloaded the 1.4.0 version from the Releases tab, then unpacked the file from `imscp-letsencrypt-1.4.0.tar.gz`, after that I renamed the folder to LetsEncrypt, then made a tar.gz archive with this command in the Terminal.app (macOS): `tar -pczf LetsEncrypt.tar.gz LetsEncrypt/`
2. I logged in with the administrator user, uploaded the plugin, then installed successfully. The status changed to 'Activated'.

Reseller and User menu and also System Tools -> Debugger:
![alt text](https://i.imgur.com/q6ByyzW.png "Error")

```
root@web:~# ls /var/www/imscp/gui/plugins/
LetsEncrypt
root@web:~# ls /var/www/imscp/gui/plugins/LetsEncrypt/
backend  CHANGELOG.md  config.php  frontend  info.php  l10n  LetsEncrypt.php  LICENSE  README.md  sql  test  themes  TODO  Vagrantfile
```
I do not know where to find the log file in the filesystem, since it is unavailable on the admin panel.

**Comment by WhiteCoreWebUI** [comment]
Installer does not create the SQL, a debug showed 
`An exception has been thrown in file /var/www/imscp/gui/library/Functions/Shared.php at line 2240:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'imscp.letsencrypt' doesn't exist

Query was:

             SELECT admin_id, admin_name FROM admin WHERE created_by = ?             AND admin_status = ? AND admin_id NOT IN (SELECT admin_id FROM letsencrypt)             ORDER BY admin_name ASC         
`

However adding:
` CREATE TABLE IF NOT EXISTS `letsencrypt` (
            `letsencrypt_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
            `admin_id` int(11) unsigned NOT NULL,
            `domain_id` int(11) unsigned NOT NULL,
            `alias_id` int(11) unsigned DEFAULT NULL,
            `subdomain_id` int(11) unsigned DEFAULT NULL,
            `cert_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
            `http_forward` tinyint(1) NOT NULL DEFAULT '0',
            `status` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
            `state` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
            PRIMARY KEY (letsencrypt_id),
            KEY letsencrypt_id (letsencrypt_id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;`

to the Database imscp fixed it, there are some backslashes that seem to cause the error, the original message when adding it manually was:

`ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '\'0\',
            `status` varchar(255) COLLATE utf8_unicode_ci NOT NULL,`

**Comment by WhiteCoreWebUI** [comment]
Also in the SQL `domain_name` and `letsencrypt_status` are missing, adding them manually fixed the issue.

**Comment by senderdc** [comment]
> 
> 
> Also in the SQL `domain_name` and `letsencrypt_status` are missing, adding them manually fixed the issue.

Yes thats missing but status is exist instead of letsencrypt_status and cert_name instead of domain_name. I think cambell-prince forgot to replace them in the php files....

**Comment by cambell-prince** [comment]
Thanks for the feedback. That's all very helpful.
