### ISSUE TITLE
Fatal error: Class 'iMSCP_Plugin_LetsEncrypt' not found

### ISSUE THREAD

**Issue by ofr0601** [saygoweb/imscp-letsencrypt#19]
I tried to install version 1.5.0 on imscp 1.5.3. If i activate the plugin, go into my customer and click on LetsEncrypt following error shows up: 

"Fatal error: Class 'iMSCP_Plugin_LetsEncrypt' not found in /var/www/imscp/gui/plugins/SGW_LetsEncrypt/frontend/client/letsencrypt.php on line 206"

Edit:

If I try to access it from the Reseller Menu I get the Error-Message: "An unexpected error occurred
Ein unerwarteter Fehler ist aufgetreten. Bitte wenden Sie sich an Ihren Administrator" and following E-Mail:

Dear administrator,

An exception has been thrown in file
/var/www/imscp/gui/library/iMSCP/pTemplate.php at line 362:

==========================================================================
Couldn't to find the
/var/www/imscp/gui/themes/default/../../plugins/LetsEncrypt/themes/default/view/reseller/letsencrypt.tpl
template file
==========================================================================

Backtrace:
__________

File: /var/www/imscp/gui/library/iMSCP/pTemplate.php at line 424
Method: iMSCP_pTemplate::get_file()
File: /var/www/imscp/gui/library/iMSCP/pTemplate.php at line 513
Method: iMSCP_pTemplate::parse_dynamic()
File:
/var/www/imscp/gui/plugins/SGW_LetsEncrypt/frontend/reseller/letsencrypt.php
at line 130
Method: iMSCP_pTemplate::parse()
File:
/var/www/imscp/gui/plugins/SGW_LetsEncrypt/frontend/reseller/letsencrypt.php
at line 145
Function: LetsEncrypt\_letsencrypt_generateCustomerList()
File:
/var/www/imscp/gui/plugins/SGW_LetsEncrypt/frontend/reseller/letsencrypt.php
at line 328
Function: LetsEncrypt\letsencrypt_generatePage()
File: /var/www/imscp/gui/public/plugins.php at line 82
Function: include()

**Comment by cambell-prince** [comment]
There is no longer any file "letsencrypt.php" in the distribution, so I'm not sure where that came from.  The plugin was renamed SGW_LetsEncrypt so the main filename is now SGW_LetsEncrypt.php not letsencrypt.php.

I suggest you delete the plugin completely and re-install.

**Comment by cambell-prince** [comment]
Or perhaps the imscp_panel service needs to be restarted `/etc/init.d/imscp_panel restart`

**Comment by maverabilisim** [comment]
Hi, I giving same error. How can I fix? 
I tried to do `/etc/init.d/imscp_panel restart` 
But there was no change.

**Comment by cambell-prince** [comment]
@maverabilisim There is no file letsencrypt.php in the current sourcecode or in the tgz release.  Can you think of how it would come to be in the plugin folder?  I've tried a clean install on 1.5.3 (on vagrant) and it works for me.  I've not tried an upgrade process myself.  I would think you would need to completely uninstall the old plugin (letsencrypt) and install the new one (SGW_LetsEncrypt) as they have different names.

I'm guessing that in these cases the plugin folder was manually renamed on the server and then the version installed "over the top" which would not erase the old code.  This would then have code that should not be present like 'letsencrypt.php'.  Or perhaps, this archive was installed over the old plugin in the letsencrypt folder which explaines why it would try loading letsencrypt.php (again, which should not be present).

The plugin should contain the files of "SGW_LetsEncrypt.tgz" and be in a folder named SGW_LetsEncrypt (case matters).

**Comment by maverabilisim** [comment]
@cambell-prince thank you for your answer and great job.
I using 1.5.3 version. I see alrady SGW_LetsEncrypt on tgz file and plugin name SGW_LetsEncrypt.

![2019-04-28_11-34-14](https://user-images.githubusercontent.com/8980578/56861471-b21ac880-69a9-11e9-8819-92823c60ed92.png)

**Comment by cambell-prince** [comment]
I think this is now fixed in 1.5.1
