### ISSUE TITLE
Plugins LetsEncrypt 

### ISSUE THREAD

**Issue by jrsalazarc** [saygoweb/imscp-letsencrypt#23]
Hello, I am using the letsencryp plugins that you have, I do the whole process perfectly and it was installed, but when generating a certificate it gave me an error when reviewing it, it told me that it did not get the letsencryp folder. I generate a symbolic link and it works.
at the beginning from the main menu I can take the client and send him to generate the certificate, it remains in the process as if something was missing.

then I go to the client directly, when trying to generate the certificate it throws me this error.

An exception has been thrown in file /var/www/imscp/gui/library/Functions/Shared.php at line 2241:

SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'domain_name' in field list is ambiguous

Query was:
SELECT domain.domain_id AS domain_id, domain_name, domain_admin_id, http_forward, status, state             FROM domain             LEFT JOIN letsencrypt ON ( domain.domain_id=letsencrypt.domain_id )             WHERE domain_admin_id = ? 

I am working on debian 9.9 and the version of imscp-1.5.3-2018120800.

Another thing is that it had to be included in the letsencrypt table, two columns, one to refer to the domain_name and the other as letencrypt_status.

**Comment by jrsalazarc** [comment]
An exception has been thrown in file /var/www/imscp/gui/library/Functions/Shared.php at line 2241:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'domain_name' in 'field list'

Query was:

INSERT INTO letsencrypt (admin_id, domain_id, domain_name, letsencrypt_status) VALUES (?, ?, ?, ?)

**Comment by cambell-prince** [comment]
Hi,

You should not have or need the field 'domain_name' in the letsencrypt table. You should not have letsencrypt_status, it should be 'status'. Perhaps you are using an old version of the plugin?

Here's what I have for the letsencrypt schema.

![image](https://user-images.githubusercontent.com/599797/98242166-9c269480-1f9e-11eb-9f12-7c8d50ccba53.png)

and version 1.5.2

![image](https://user-images.githubusercontent.com/599797/98242276-c8421580-1f9e-11eb-9eb5-f27135ae82ab.png)

**Comment by cambell-prince** [comment]
Sounds like issue #16 which has been fixed.
