### ISSUE TITLE
LE - DST Root CA X3 Expiration

### ISSUE THREAD

**Issue by clusterx** [saygoweb/imscp-letsencrypt#26]
does the plugin work after the LE DST Root CA X3 Expiration - I mean is LE ISRG Root X1 supported?
details:
[https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/](url)

**Comment by cambell-prince** [comment]
The plugin uses certbot to create / update LetsEncrypt certificates.  If you're installed certbot works then the plugin will work.  If you have an old certbot (e.g. certbot-auto) then perhaps not.  The plugin does not manage the upgrade of certbot for you - you need to do that manually on your server.
