### ISSUE TITLE
i-MSCP 1.5.1 not working

### ISSUE THREAD

**Issue by GrexAut** [saygoweb/imscp-letsencrypt#9]
At installation follow message appears:
imscp-letsencrypt-1.1.1/imscp-letsencrypt-1.1.1.php scheint kein i-MSCP Plugin-Archiv zu sein.

Can you confirm it isn't compatible with i-MSCP 1.5.1?

**Comment by cambell-prince** [comment]
It possibly is not compatible.  I'm currently using it with 1.3.x series which is listed as a requirement in the README.md.

I have the plugin in a folder called `LetsEncrypt` it may be that by uploading a versioned archive from GitHub its not installed with the right folder name.  Try it as LetsEncrypt.zip or manually change the folder name and it might at least get further than that.

**Comment by cambell-prince** [comment]
I think version 1.4.0 of the plugin should be compatible with i-MSCP 1.5.x if you'd like to try it.

**Comment by MuhKuh7** [comment]
Same error with version 1.4.0 and i-MSCP 1.5.3. Any ideas?
Edit: Didn't see the part about the renaming... Yes, you need to rename the folder in the tar.gz to LetsEncrypt, otherwise it looks for the wrong php file.

**Comment by cambell-prince** [comment]
Version 1.5.x fixes #16 issues with installation and configuration on iMSCP 1.4.x and 1.5.x.
